services:
  - type: web
    name: book-management
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: ASSET_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: DB_SCHEMA
        value: laravel
      - key: JWT_SECRET
        sync: false
      - key: L5_SWAGGER_GENERATE_ALWAYS
        value: "false"
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_DAILY_DAYS
        value: "14"
      - key: API_BOOKS_CACHE_TTL
        value: "60"
      - key: API_LOG_SUCCESS
        value: "false"
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_URL
        sync: false
      - key: QUEUE_CONNECTION
        value: sync
      - key: RUN_MIGRATIONS
        value: "false"
